name: Deploy to InfinityFree (parametric-static)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'parametric-static/**'
      - '.github/workflows/deploy-infinityfree.yml'
  workflow_dispatch: {}

concurrency:
  group: deploy-infinityfree
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy-ftps:
    name: Deploy over FTPS (explicit :21)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: FTPS deploy (parametric-static → /htdocs)
        id: ftps
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server:     ${{ secrets.INF_FTP_HOST }}   # ftpupload.net
          username:   ${{ secrets.INF_FTP_USER }}   # e.g. if0_39735787
          password:   ${{ secrets.INF_FTP_PASS }}
          protocol:   ftps
          port:       21
          local-dir:  parametric-static/
          server-dir: /htdocs/
          log-level:  verbose
          exclude: |
            scripts/**
            scripts.__bak__*/**
            **/*.ps1
            **/*.psm1
            **/*.bat
            **/*.cmd
            **/*.sh
            **/*.py
            **/*.exe
            **/*.dll
            **/*.msi
            **/.DS_Store
            **/Thumbs.db

  deploy-ftp-fallback:
    name: Fallback deploy over plain FTP (insecure)
    needs: deploy-ftps
    if: needs.deploy-ftps.result == 'failure'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: FTP deploy (parametric-static → disposable-vape-nation.42web.io/htdocs)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server:     ${{ secrets.INF_FTP_HOST }}
          username:   ${{ secrets.INF_FTP_USER }}
          password:   ${{ secrets.INF_FTP_PASS }}
          protocol:   ftp
          port:       21
          local-dir:  parametric-static/
          server-dir: /htdocs/
          log-level:  verbose
          exclude: |
            scripts/**
            scripts.__bak__*/**
            **/*.ps1
            **/*.psm1
            **/*.bat
            **/*.cmd
            **/*.sh
            **/*.py
            **/*.exe
            **/*.dll
            **/*.msi
            **/.DS_Store
            **/Thumbs.db
